name: Daily students.csv upload to S3

on:
  schedule:
    - cron: "0 12 * * *"   # 21:00 UTC = 4 pm Colombia
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Load Dependencies
        run: |
          pip install boto3 pandas pyarrow

      - name: Loading Aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Copy students.csv in Downloads
        run: |
          mkdir -p ~/Downloads
          cp students.csv ~/Downloads/students.csv

      - name: Run uppload python script
        run: python students_s3.py